server:
   accessPath: http://127.0.0.1:16100/ap_fb
spring:
   datasource:
      driverUrl: jdbc:oracle:thin:@127.0.0.1:1521:orcl
      driver: oracle.jdbc.driver.OracleDriver
      dialect: org.hibernate.dialect.Oracle10gDialect
      user: ap_fb
      password: ap123#
viewInformation:
   title: AgileProduction 敏捷生产 V7.6
   profile: 《油气生产敏捷计算分析系统 V7.6》 主要针对泵设备和管设备系列产品，通过驱动配置，实现采集、控制与报警等功能。模块包括实时监控、历史查询、故障查询、日志查询、权限管理（单位管理、用户管理、角色管理）、设备管理（泵设备、管设备、短信设备）、驱动配置（协议配置、实例配置）和系统配置（模块配置、字典配置、报警配置）等功能。
   copy: ""
   linkaddress: http://www.cosogoil.com
   linkshow: ""
agileCalculate:
   probe:
      app: 
       - http://8.130.30.138:18100/api/probe/app
      mem: 
       - http://8.130.30.138:18100/api/probe/mem
      disk: 
       - http://8.130.30.138:18100/api/probe/disk
      host: 
       - http://8.130.30.138:18100/api/probe/host
      cpu: 
       - http://8.130.30.138:18100/api/probe/cpu
   FESDiagram: 
    - http://8.130.30.138:18100/api/calc/rpc/fesdiagram/pro
   FSDiagram: 
    - http://8.130.30.138:18100/api/calc/rpc/fsdiagram/balance/back
   ESDiagram:
      balance: 
       - http://8.130.30.138:18100/api/calc/rpc/esdiagram/balance/back
      inversion:
         inversionSwitch: false
         url:
            motorauto: 
             - http://8.130.30.138:18100/api/calc/rpc/esdiagram/inversion/motorauto
            motorsemiauto: 
             - http://8.130.30.138:18100/api/calc/rpc/esdiagram/inversion/motorsemiauto
            beam: 
             - http://8.130.30.138:18100/api/calc/rpc/esdiagram/inversion/beam
         timerCorrectionStart: 06:00:00
         imerCorrectionEnd: 21:00:00
         timerCorrectionLimit: 1800
   pcpProduction: 
    - http://8.130.30.138:18100/api/calc/pcp/rpm
   communication: 
    - http://8.130.30.138:18100/api/calc/plugin/timeeff/comm
   run: 
    - http://8.130.30.138:18100/api/calc/plugin/timeeff/run
   energy: 
    - http://8.130.30.138:18100/api/calc/plugin/energy
   totalCalculation:
      well: 
       - http://8.130.30.138:18100/api/analy/total/well
   plugin: 
      wellboreTrajectory: http://8.130.30.138:18100/api/calc/plugin/2xyz
      fa2fs: http://8.130.30.138:18100/api/plugin/fa2fs
tcpServer:
   port: 19100
mqtt:
   server: tcp://dq1c6knb.hinnotek.cn:1883
   userName: hinnotekClient1
   passWord: ZJ6m*#D4pd%b
driverConfig:
   server: http://8.130.30.138:19200/api/init/server
   protocol: http://8.130.30.138:19200/api/init/protocol
   instance: http://8.130.30.138:19200/api/init/instance
   id: http://8.130.30.138:19200/api/init/id
   SMS: http://8.130.30.138:19200/api/init/sms
   readAddr: http://8.130.30.138:19200/api/read/addr
   writeAddr: http://8.130.30.138:19200/api/write/addr
   writeSMS: http://8.130.30.138:19200/api/write/sms
   probe:
      init: 
         http://8.130.30.138:19200/api/probe/init
      cpu: 
         http://8.130.30.138:19200/api/probe/cpu
      mem: 
         http://8.130.30.138:19200/api/probe/mem
      disk: 
         http://8.130.30.138:19200/api/probe/disk
      host: 
         http://8.130.30.138:19200/api/probe/host
others:
   cache: false
   language: zh_CN
   pageSize: 100
   syncOrAsync: false
   expandedAll: true
   defaultComboxSize: 10000
   defaultGraghSize: 60
   productionUnit: 1
   serialnumber: God bless you!
      